name = "JuliaMBDv1"
uuid = "4cf2e3c0-9b22-4ab0-a6e0-5dafb67aefd6"
authors = ["Hiroyuki Okamura"]
version = "0.1.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
